spring:
  profiles:
    active:
    - dev
   
---

#开发环境
spring
  profiles: dev  
  application:
    name: microservicecloud-config-cincc-dev
  
---

#测试环境
spring:
  profiles: test  
  application:
    name: microservicecloud-config-cincc-test
 
 
 #文件一定要保存为UTF-8格式